name: mini_market
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.7.2
  http: ^1.3.0
  shared_preferences: ^2.2.2

  iconsax: ^0.0.8
  readmore: ^3.0.0
  collection: ^1.17.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
